# Generated by Django 5.1.8 on 2025-04-26 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_ssd_large_wholesale_min_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('shipped', 'Отгружена')],
                    default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                            verbose_name='Менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_at_add',
                 models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент добавления')),
                ('cart',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart',
                                   verbose_name='Партия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ssd',
                                              verbose_name='Товар')),
            ],
        ),
    ]
