# Generated by Django 5.1.8 on 2025-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_formfactor_interface_alter_ssd_form_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssd',
            name='large_wholesale_min_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мин. количество для крупного опта'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='large_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True,
                                      verbose_name='Цена за крупный опт'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='small_wholesale_min_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мин. количество для мелкого опта'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='small_wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True,
                                      verbose_name='Цена за мелкий опт'),
        ),
    ]
