# Generated by Django 5.1.7 on 2025-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('capacity_gb', models.PositiveIntegerField(verbose_name='Ёмкость (ГБ)')),
                ('interface', models.CharField(choices=[('SATA', 'SATA'), ('NVMe', 'NVMe PCIe')], max_length=20,
                                               verbose_name='Интерфейс')),
                ('form_factor', models.CharField(choices=[('2.5"', '2.5"'), ('M.2', 'M.2')], max_length=20,
                                                 verbose_name='Форм-фактор')),
                ('read_speed', models.PositiveIntegerField(verbose_name='Скорость чтения (МБ/с)')),
                ('write_speed', models.PositiveIntegerField(verbose_name='Скорость записи (МБ/с)')),
                ('warranty_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия (лет)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
        ),
    ]
